# Generated by Django 3.2.8 on 2021-10-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
