# Generated by Django 3.2.8 on 2021-10-31 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0005_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='textline',
            field=models.CharField(default=0, max_length=50, validators=[django.core.validators.MaxLengthValidator(limit_value=50, message=' no more than 50 char')]),
            preserve_default=False,
        ),
    ]
