# Generated by Django 3.2.8 on 2021-10-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0006_auto_20211031_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='textline',
            field=models.CharField(max_length=20),
        ),
    ]
