# Generated by Django 3.2.8 on 2021-10-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0007_alter_post_textline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='textline',
            field=models.CharField(max_length=280),
        ),
    ]
